server:
  port: 8081

spring:
  application:
    name: security-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ucsal_controle_academico?currentSchema=security}
    username: ${SPRING_DATASOURCE_USERNAME:ucsal_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: security
    create-schema: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:chave_secreta_compartilhada_de_producao_256bits_minimo}
